-- 1TechLink Social Hub - Schema (PostgreSQL)
--
-- Fresh-install reference. Destructive (DROP TABLE) — never run against a
-- live database. For incremental changes use database/migrations/ via
--   php scripts/migrate.php
-- then import demo data with database/seed.sql.

DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS analytics;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS post_publications;
DROP TABLE IF EXISTS post_platforms;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS social_accounts;
DROP TABLE IF EXISTS social_platforms;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS settings;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role TEXT NOT NULL DEFAULT 'content_manager'
    CONSTRAINT users_role_check CHECK (role IN ('admin', 'content_manager')),
  avatar VARCHAR(255) NULL,
  is_active BOOLEAN DEFAULT TRUE,
  last_login_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE social_platforms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  icon VARCHAR(50) NULL,
  color VARCHAR(20) NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE social_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_id INTEGER NOT NULL,
  user_id INTEGER NULL,
  account_name VARCHAR(150) NOT NULL,
  username VARCHAR(150) NOT NULL,
  account_type VARCHAR(50) DEFAULT 'page',
  access_token TEXT NULL,
  refresh_token TEXT NULL,
  scopes TEXT NULL,
  token_expires_at TIMESTAMP NULL,
  external_user_id VARCHAR(190) NULL,
  external_account_id VARCHAR(190) NULL,
  avatar_url VARCHAR(500) NULL,
  connection_status TEXT DEFAULT 'connected'
    CONSTRAINT sa_status_check CHECK (connection_status IN ('connected', 'disconnected', 'expired', 'error')),
  last_error TEXT NULL,
  followers INTEGER DEFAULT 0,
  following INTEGER DEFAULT 0,
  posts_count INTEGER DEFAULT 0,
  engagement_rate DECIMAL(5,2) DEFAULT 0.00,
  last_synced_at TIMESTAMP NULL,
  meta JSONB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (platform_id) REFERENCES social_platforms(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_sa_platform_status ON social_accounts (platform_id, connection_status);
CREATE INDEX IF NOT EXISTS idx_sa_external ON social_accounts (platform_id, external_account_id);

CREATE TABLE media (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  filename VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_type VARCHAR(100) NOT NULL,
  file_size INTEGER NOT NULL,
  width INTEGER NULL,
  height INTEGER NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  hashtags VARCHAR(500) NULL,
  media_ids JSONB NULL,
  status TEXT DEFAULT 'draft'
    CONSTRAINT posts_status_check CHECK (status IN ('draft', 'scheduled', 'publishing', 'published', 'failed', 'partial')),
  scheduled_at TIMESTAMP NULL,
  published_at TIMESTAMP NULL,
  publish_locked_at TIMESTAMP NULL,
  publish_token CHAR(36) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_posts_sched ON posts (status, scheduled_at);

CREATE TABLE post_platforms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL,
  platform_id INTEGER NOT NULL,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (platform_id) REFERENCES social_platforms(id) ON DELETE CASCADE,
  CONSTRAINT uniq_post_platform UNIQUE (post_id, platform_id)
);

CREATE TABLE post_publications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id INTEGER NOT NULL,
  platform_id INTEGER NOT NULL,
  account_id INTEGER NULL,
  status TEXT DEFAULT 'pending'
    CONSTRAINT pp_status_check CHECK (status IN ('pending', 'published', 'failed', 'scheduled')),
  external_post_id VARCHAR(255) NULL,
  permalink VARCHAR(500) NULL,
  error_message TEXT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  locked_at TIMESTAMP NULL,
  next_retry_at TIMESTAMP NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (platform_id) REFERENCES social_platforms(id) ON DELETE CASCADE,
  FOREIGN KEY (account_id) REFERENCES social_accounts(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_pp_retry ON post_publications (status, next_retry_at);

CREATE TABLE notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_id INTEGER NULL,
  account_id INTEGER NULL,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  meta JSONB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (platform_id) REFERENCES social_platforms(id) ON DELETE SET NULL,
  FOREIGN KEY (account_id) REFERENCES social_accounts(id) ON DELETE SET NULL
);

CREATE TABLE analytics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform_id INTEGER NOT NULL,
  account_id INTEGER NULL,
  date DATE NOT NULL,
  followers INTEGER DEFAULT 0,
  follower_growth INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  saves INTEGER DEFAULT 0,
  reach INTEGER DEFAULT 0,
  impressions INTEGER DEFAULT 0,
  engagement_rate DECIMAL(5,2) DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (platform_id) REFERENCES social_platforms(id) ON DELETE CASCADE,
  FOREIGN KEY (account_id) REFERENCES social_accounts(id) ON DELETE SET NULL,
  CONSTRAINT uniq_platform_date UNIQUE (platform_id, date)
);

CREATE TABLE activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NULL,
  action VARCHAR(100) NOT NULL,
  description TEXT NULL,
  ip_address VARCHAR(45) NULL,
  meta JSONB NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE rate_limits (
  rate_key VARCHAR(190) NOT NULL PRIMARY KEY,
  hits INTEGER NOT NULL DEFAULT 0,
  window_start BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_window ON rate_limits (window_start);

CREATE TABLE settings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "key" VARCHAR(100) NOT NULL UNIQUE,
  "value" TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
